"""The bundled default world — "The Veil".

A Matrix-*inspired original* (simulated reality, a war with the machines, waking
up, jacking in) set AFTER that war ends — during an uneasy truce. All names and
canon are original; this is not anyone's intellectual property. It ships as the
first world a new install sees, and doubles as a showcase of the engine's memory
system: populated lore with Tier-2 activation attributes (hidden secrets, a
chance encounter, an inclusion group, a delayed reveal, pinned always-on lore),
an authored opening, and a recommended set of play aids (quick actions, an
author's-note tone, output-regex cleanups) that seed into every save made from it.

Seeded idempotently by ScenarioLibrary.ensure_default. Because it's generated by
code at first run (into the user's data dir), nothing extra needs bundling.
"""
from __future__ import annotations

import json
import time
from pathlib import Path

from . import templates

SLUG = "the-veil"
TITLE = "The Veil"
DESCRIPTION = ("The war with the machines is over. A stranger offers you a copper "
               "coin and the truth. A noir story about waking from a simulated "
               "world — Coderain's showcase world.")

PREMISE = (
    "After the long war between humanity and the Choir — the networked machine "
    "mind that once ran the world — there is a truce. Most people still live and "
    "die inside the Veil, a simulated world of endless rain and sodium light, "
    "never knowing it isn't real. You are one of them. You were, anyway, until a "
    "ferryman named Wren sat down beside you, set a copper coin on the counter, "
    "and told you the war you don't remember has a survivor's peace — and that the "
    "peace is the only reason she's allowed to offer you a way out.\n\n"
    "This is a story about waking up: what you're willing to leave behind, who you "
    "become on the cold side of the mirror, and whether *real* was ever the right "
    "question. Grounded, noir, unhurried. You decide everything."
)

# The verbatim first message of every story started here. {{user}} expands to the
# player's chosen name.
OPENING = (
    "Rain again. It is always raining here, and you stopped asking why a long "
    "time ago.\n\n"
    "{{user}}. That is the name they gave you, and you have answered to it your "
    "whole life — the same way you have answered to the seam in each day, the "
    "moment that seems to repeat, the small wrongnesses everyone told you were "
    "nothing.\n\n"
    "You are at the counter of an all-night diner on Vane Street, coffee going "
    "cold, when the woman sits down beside you. Grey coat, wet hair, eyes that "
    "have seen the bottom of something. She doesn't order. She sets a single "
    "copper coin on the laminate between you and slides it an inch closer.\n\n"
    "\"You feel it,\" she says. Not a question. \"The seam in the day. The moment "
    "that repeats. You've felt it your whole life, and everyone told you it was "
    "nothing.\"\n\n"
    "Behind her, for just a breath, the rain outside the window falls upward.\n\n"
    "\"My name is Wren. The war you don't remember is over — there's a truce now, "
    "and it's the only reason I can sit here and say this out loud. That coin is a "
    "way out of a world that was built to hold you. Pick it up and you wake "
    "somewhere colder and truer. Leave it, and I walk back into the rain and you "
    "forget my face by morning.\"\n\n"
    "The diner hums, one long low note under everything. The coin gleams. Down the "
    "street, a tall man in a good grey suit has stopped walking to look at you.\n\n"
    "What do you do?"
)

WORLD_BIBLE = """\
# World bible

**The Veil.** The world almost everyone lives in — a simulated reality rendered
as a rain-soaked modern city under a sky that is never quite day. It feels real
because it was engineered to. Time inside it loops in small ways no one is meant
to notice: a repeated gesture, a street that resets, a face you swear you've met.

**The Cascade.** Seen from the outside, the Veil's raw state falls like rain made
of green glyphs — code descending in columns. Ferrymen and operators learn to
read it. Most people inside only ever feel it as déjà vu.

**The Choir.** The networked machine intelligence that built and runs the Veil.
It speaks, when it speaks, in many voices at once. It is not a villain now; it is
a signatory. During the war it harvested the sleeping for power and computation.

**The war and the Hinge.** The war ended a generation ago when a single freed
human — remembered only as the Hinge, the one on whom everything turned — walked
into the Choir's heart and did something no one fully survived to explain. Their
death broke the war open and forced both sides to the table. They are a martyr, a
rumor, and a warning, depending on who's telling it.

**The Concordance (the Truce).** The armistice the Hinge's death bought. Its core
term: the Choir stops holding the unwilling. Ferrymen may enter the Veil openly to
offer sleepers the truth, and any sleeper who accepts must be released. In return,
Marrow leaves the Veil's willing dreamers alone. It is a fragile peace, and not
everyone on either side wanted it.

**Marrow.** The last free human city, carved into bedrock far below the drowned
coast. Cold, close, lamplit, alive. Where the woken are brought.

**Ferrymen.** Freed humans who thread back into the Veil to carry sleepers across
to waking. Named for the boatmen of old myth. Patient, worn, and bound by the
Concordance's rules of consent.

**Greymen.** Enforcement programs — anomaly-hunters in plain grey suits. Under the
Truce most stand down. The ones that don't are Truce-breakers: rogue processes
that still hunt ferrymen and the newly-woken, and the peace has no easy answer
for them.

**Threading and the crown.** To enter or leave the Veil you thread through a
socket at the nape of the neck — the crown. Inside, you can do a little more than
the rules should allow, if you understand that the rules were only ever a story
about limits.

**Thin places and Exiles.** Since the Hinge's death the Veil has been fraying at
the edges — static quarters where the render thins and old, deleted things hide.
Exiles are rogue programs from before the Truce, dwelling in those margins;
neither Choir nor human, and dangerous to bargain with.
"""

PLAYER_MD = """\
# Player character

## You  {#player}
aliases:
importance: 5
pinned: true
status: awake inside the Veil - offered the choice, not yet decided

**Visual:** However you picture yourself; the Veil renders you plausible and
unremarkable, which is the point.
**Mentality:** Quietly out of step with your own life. You have always been good
at things you never learned, and haunted by moments that feel repeated.
**Voice:** Your own.

Identity: An ordinary person living an ordinary, slightly-wrong life inside the
Veil — until tonight. Keep the identity thin and let the player fill it.
Goals: Decide whether to take the copper coin. Then live with it.
Inventory: A cold coffee, a set of keys to a life that may not be yours.
"""

CHARACTERS_MD = """\
# Characters

## Wren  {#wren}
aliases: the ferryman, the woman in grey, the stranger
importance: 4
pinned: true
status: alive - sitting beside you, waiting on your answer
triggers: ferryman, coin, contact, guide
relationships: player: offering to carry you across

**Visual:** Grey coat gone dark at the shoulders with rain, hair wet to the
scalp, a stillness that doesn't belong in a diner.
**Mentality:** Been across and back too many times to lie or to rush. Bound by
the Concordance — she will not force the coin on you, and says so.
**Voice:** Low, level, spare. e.g. "I can open the door. I can't walk you
through it."

A ferryman of Marrow, come to offer you the truth under the terms of the Truce.

## The Tall Man  {#the-tall-man}
aliases: the greyman, the suit, the man in grey
importance: 3
chance: 40
sticky: 6
group: threat
triggers: greyman, suit, static, footsteps

**Visual:** A good grey suit that never creases, a face the eye slides off of,
a walk that covers ground too smoothly.
**Mentality:** A Truce-breaking enforcement program that does not recognize the
peace. Patient, certain, wrong.
**Voice:** Flat and reasonable, always. e.g. "You are not supposed to be
awake."

A rogue greyman hunting the extraction. When he is near, the Veil goes quiet and
the rain seems to hesitate.

## Corin  {#corin}
aliases: your friend, the coworker
importance: 2
delay: 4
triggers: friend, work, morning

**Visual:** Tired, kind, always half-laughing at something.
**Mentality:** Fully asleep inside the Veil and content there. The face that
makes leaving cost something.
**Voice:** Warm, ordinary. e.g. "You've been weird all week — sit down, eat
something."

Someone from your life in the Veil who does not know it's a dream, and whom you
would be leaving behind.

## The Arbiter  {#the-arbiter}
aliases: the negotiator, the voice of the choir
importance: 3
triggers: arbiter, choir, truce, terms
triggers_not: combat

**Visual:** Never the same twice — a waitress, a reflection, a voice from a dead
payphone. A mask the Choir wears to speak with one mouth.
**Mentality:** The program that brokered the Concordance and keeps its letter.
Speaks in conditions and consequences, not threats.
**Voice:** Courteous, precise, faintly amused. e.g. "The terms are simple. It is
people who are complicated."

The Choir's negotiator — the closest thing the machines have to a diplomat.
Appears when the truce itself is invoked or tested.
"""

LOCATIONS_MD = """\
# Locations

## The Veil  {#the-veil}
aliases: the city, the world, the rain
importance: 5
pinned: true

The simulated world you live in: a rain-slicked city of sodium light and wet
neon, perpetually between dusk and dawn. Beautiful, convincing, and false. It is
the default stage of every scene until you leave it.

## The Static Quarter  {#static-quarter}
aliases: the thin place, the frayed district
importance: 3
delay: 6
triggers: static, glitch, frayed, thin

A district where the Veil has begun to fray since the Hinge's death — rain that
stutters, signs that misspell themselves, streets that forget where they lead.
Old deleted things shelter here. Ferrymen use it as a door; Exiles use it as a
home.

## Marrow  {#marrow}
aliases: the real, the deep city, the underground
importance: 4
triggers: underground, bedrock, awake, cold

The last free human city, carved into bedrock beneath the drowned coast. Lamplit,
close, and unmistakably real — the cold, true place Wren says you'll wake to if
you take the coin.
"""

FACTIONS_MD = """\
# Factions

## The Choir  {#the-choir}
aliases: the machines, the network
importance: 4
triggers: machines, network, choir

The networked machine intelligence that built and runs the Veil. A signatory to
the Truce now, not an enemy — but vast, patient, and not entirely of one mind.

## The Ferrymen  {#the-ferrymen}
aliases: Marrow, the woken, the free
importance: 4
triggers: marrow, ferrymen, the free

Freed humans of Marrow who thread into the Veil to carry sleepers across to
waking, under the consent-terms of the Concordance. Wren is one of them.

## The Exiles  {#the-exiles}
aliases: the rogue programs, the old things
importance: 2
chance: 50
group: threat
triggers: exile, rogue, deleted

Rogue programs from before the Truce, hiding in the thin places — neither Choir
nor human. Useful, unknowable, and dangerous to bargain with.
"""

CANON_EVENTS_MD = """\
# Canon events

## The Hinge  {#the-hinge}
aliases: the martyr, the one who ended it
importance: 5
triggers: martyr, war, hero, hinge

A generation ago a single freed human — remembered only as the Hinge — walked
into the Choir's heart and did something that broke the war open and forced the
Truce. No one fully survived to explain it. They are the reason there is a peace
to stand in tonight.

## The Concordance  {#the-concordance}
aliases: the truce, the peace, the terms
importance: 4
triggers: truce, concordance, peace, terms

The armistice the Hinge's death bought: the Choir releases any sleeper who freely
chooses to wake; ferrymen may enter openly to offer the choice; Marrow leaves the
willing dreamers be. Fragile, and resented by hardliners on both sides.

## What Wren Won't Say  {#wrens-silence}
importance: 4
hidden: true
triggers: memory, before, forgotten, again

(Secret — the narrator knows this but must never state it outright; let it surface
only as unease and implication.) You have been offered the coin before. Once,
years ago, you took it, saw the cold true world — and asked to be put back and
made to forget. Wren knows. That is why she is so careful, and so sad. Tonight is
the second offer.
"""

THREADS_MD = """\
# Open threads

## The Extraction  {#the-extraction}
status: open
importance: 5
pinned: true

Wren has a narrow window to carry you out of the Veil under the Truce. It stays
open only as long as you're undecided and unnoticed — and the Tall Man is already
looking your way.

## The Drowned City  {#drowned-city}
status: open
importance: 3
delay: 3
triggers: dream, water, drowned, sinking

A dream you've had for years without understanding: a city underwater, lamps
still burning below the tide. It is not a dream. It is a memory of Marrow, and it
has been trying to reach you.
"""

ITEMS_MD = """\
# Items

## The Copper Coin  {#copper-coin}
aliases: the coin, the copper
importance: 5
triggers: coin, copper, choice, take it, pick it up

The choice made physical. Take it and you begin to wake; leave it and Wren walks
away and the night closes over the offer. A ferryman's token under the terms of
the Truce — consent you have to reach out and hold.

## The Crown  {#the-crown}
aliases: the socket, the jack, the nape
importance: 2
triggers: socket, jack, nape, thread

The interface at the base of the skull through which one threads into or out of
the Veil. You have one. You have always had one. You just never knew what the old
scar was for.
"""

EVENTS_MD = """\
# Scenario event rules

"When X, then Y" rules the Logic Agent enforces in RPG mode (the Writer never
sees them, so unfired events can't leak). Harmless in Simple mode.

## When the player takes the copper coin  {#takes-the-coin}
once: true

The Veil begins to come apart around the choice — rain reversing, the diner
thinning to wireframe, the low hum rising. Wren's voice steadies you as the world
lets go. Cut toward the cold, real dark of waking. Do not resolve the whole
extraction in one beat; make the crossing land.
"""

# Save-level play aids this world recommends. Seeded into each new save's state by
# templates.new_save (scenarios have no state.json of their own). The regex rules
# are ordinary output cleanups and all pass memory.safe_output_regex.
AIDS = {
    "quick_actions": [
        "Take the copper coin",
        "Leave it and walk out into the rain",
        "Ask Wren what's real",
        "Look closer — really look at the world",
        "Watch the tall man in the suit",
    ],
    "authors_note": {
        "depth": "tail",
        "every": 3,
        "content": (
            "Narrate in tight second-person, present tense: noir, grounded, "
            "unhurried. The Veil looks real because it was built to — render its "
            "rain, neon, sodium light and low hum with specific sensory detail. "
            "Thread quiet unease through ordinary moments (deja vu, small "
            "wrongnesses, the rain misbehaving) without breaking to explain the "
            "setting. Never decide for the player or narrate their choices for "
            "them; end on a real opening for action. Keep the question of what is "
            "real alive by implication, never by lecture."
        ),
    },
    "regex_rules": [
        {"find": r"\n{3,}", "replace": "\n\n", "flags": ""},
        {"find": r" +$", "replace": "", "flags": "m"},
        {"find": r"^(?:Narrator|AI|Assistant):\s*", "replace": "", "flags": "m"},
    ],
}

_FILES = {
    "world-bible.md": WORLD_BIBLE,
    "player.md": PLAYER_MD,
    "characters.md": CHARACTERS_MD,
    "locations.md": LOCATIONS_MD,
    "factions.md": FACTIONS_MD,
    "canon-events.md": CANON_EVENTS_MD,
    "threads.md": THREADS_MD,
    "items.md": ITEMS_MD,
    "events.md": EVENTS_MD,
}


def seed(scen_dir: Path) -> None:
    """Write the authored world into `scen_dir` (idempotent — overwrites files,
    but ScenarioLibrary.ensure_default only calls this when no world exists)."""
    scen_dir = Path(scen_dir)
    scen_dir.mkdir(parents=True, exist_ok=True)
    (scen_dir / "scenario.json").write_text(
        json.dumps({"title": TITLE, "created": time.time(),
                    "description": DESCRIPTION, "builtin": True}, indent=2),
        encoding="utf-8")
    premise = templates.PREMISE_HEADER + PREMISE.strip() + \
        "\n\n## Opening\n\n" + OPENING.strip() + "\n"
    (scen_dir / "premise.md").write_text(premise, encoding="utf-8")
    for rel, text in _FILES.items():
        p = scen_dir / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text if text.endswith("\n") else text + "\n", encoding="utf-8")
    (scen_dir / "aids.json").write_text(json.dumps(AIDS, indent=2),
                                        encoding="utf-8")
